# Generated by Django 4.1.6 on 2023-02-09 02:45

from django.db import migrations, models
import django_namespaces.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_namespaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namespace',
            options={'ordering': ['slug', '-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='namespace',
            name='slug',
            field=models.SlugField(help_text='Namespaces must be unique across this Django project.', unique=True, validators=[django_namespaces.validators.valid_project_id]),
        ),
    ]
