# Generated by Django 4.1.6 on 2023-03-15 14:45

from django.db import migrations, models
import django_namespaces.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_namespaces', '0002_alter_namespace_options_alter_namespace_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespace',
            name='slug',
            field=models.SlugField(help_text='Namespaces must be unique across this website.', unique=True, validators=[django_namespaces.validators.valid_project_id]),
        ),
    ]
