# Generated by Django 5.1.4 on 2025-01-13 20:10
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("django_namespaces", "0005_namespace_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namespace",
            name="default",
            field=models.BooleanField(
                default=True,
                help_text="Default namespace for this user (only one possible)",
            ),
        ),
    ]
