# Generated by Django 5.1.4 on 2025-01-14 06:11
from __future__ import annotations

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import django_namespaces.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "handle",
                    models.SlugField(
                        help_text="Namespaces must be unique across this website.",
                        unique=True,
                        validators=[django_namespaces.validators.valid_project_id],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
