# Generated by Django 5.1.4 on 2025-01-14 07:26
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="namespace",
            name="user",
        ),
    ]
